#!/usr/bin/env python3
"""
WHAT THIS GENERATES IS NOT THE SHIPPED CHIP (marked 2026-08-16).
gen_chain.py emits a THREE-cell chain with continuous, geometry-ratioed
mirror couplings.  The die has TWO cells and 4-bit signed radix-4 MDAC
couplings (16 levels, LSB 1/4 unit).  The linearisation figure this deck
produced -- "residual 0.0027 units rms (1.1 % of span)" -- is therefore
UNVALIDATED for the fabricated part; see the header of the generated
toplevel/chain_full.spice.  Regenerating and re-running does not fix
that: it re-measures the same non-shipped circuit.
"""
"""Generate the full-silicon beta-model thermistor chain deck:
PTAT bias + 3 real cells + real mirror-implemented weights.

This is the seed of the config compiler: it owns the bookkeeping between
TARGET weights (the math) and PHYSICAL legs (pedestal +2, reference /3,
inter-cell +6-unit output offsets, TIA inversion, mirror polarities).

Math (beta-model, s=300, in cell units):
  cell A: exp off (u=-6);  veff_A = x            -> out_A = -ln(x/3)
  cell B: exp off;  veff_B = 3.3072 - 0.2620*out_A
                                     -> out_B = -ln(v_B_target)
  cell C: u_C = out_B; veff_C = 3    -> out_C = 1/v_B_target = T/s
Physical: every out node gets +6 units (unipolarity); consuming alphas
compensate. All constant legs L=8, W = 4*(units). Mirror pairs L=2.
"""
import math

IU = 0.5e-6
HDR = """* GENERATED by gen_chain.py -- full-silicon beta-model thermistor chain
.lib /Users/cteusche/.ciel/sky130A/libs.tech/ngspice/sky130.lib.spice tt

VDD vdd 0 3.3
XBIAS vdd pbias vrefb ve ptatbias
XLMON nmon pbias vdd vdd sky130_fd_pr__pfet_g5v0d10v5 W=4 L=8
VMON nmon 0 1.0

* bench input: x as current into cell A's v-node (beta_A = 1 direct)
IX 0 nva_in 0.5u

* ---- cells ----
XCA nua nva_in outa vdd vrefb ve pbias emlcell_b
XCB nub nvb_in outb vdd vrefb ve pbias emlcell_b
XCC nuc nvc_in outc vdd vrefb ve pbias emlcell_b
VOUTC outc 0 0.9
"""

def pleg(name, node, units):
    w = 4.0 * units
    return f"XP{name} {node} pbias vdd vdd sky130_fd_pr__pfet_g5v0d10v5 W={w:.3f} L=8"

def nsink(name, node, units):
    """constant sink: PMOS leg -> NMOS mirror pulling from node.
    Senses on both the feed and the output legs."""
    w = 4.0 * units
    return "\n".join([
        f"XPS{name} f{name} pbias vdd vdd sky130_fd_pr__pfet_g5v0d10v5 W={w:.3f} L=8",
        f"VSP{name} f{name} nd{name} 0",
        f"XN1{name} nd{name} nd{name} 0 0 sky130_fd_pr__nfet_g5v0d10v5 W=16 L=2",
        f"XN2{name} o{name} nd{name} 0 0 sky130_fd_pr__nfet_g5v0d10v5 W=16 L=2",
        f"VSN{name} {node} o{name} 0",
    ])

def gmirror(name, src_node, dst_node, ratio):
    """weighted sink mirror: pulls ratio*(I at src diode) from dst_node.
    Sense source in the diode leg for observability."""
    wout = 16.0 * ratio
    return "\n".join([
        f"VSD{name} {src_node} {src_node}d 0",
        f"XGD{name} {src_node}d {src_node}d 0 0 sky130_fd_pr__nfet_g5v0d10v5 W=16 L=2",
        f"XGO{name} {dst_node} {src_node}d 0 0 sky130_fd_pr__nfet_g5v0d10v5 W={wout:.3f} L=2",
    ])

body = [HDR]
# cell A: exp off (u=-6 -> +6 units INTO nua), alpha_v = -2 (sink 2u)
body.append(pleg("UA", "nua", 6.0))
body.append(nsink("AV", "nva_in", 2.0))
# out_A offset +6
body.append(pleg("OA", "outa", 6.0))

# cell B: exp off; gamma via mirror ratio 0.2620 sinking from nvb_in;
# alpha leg = 3.3072 - 2 (ped) + 0.2620*6 (offset comp) = 2.879 units
body.append(pleg("UB", "nub", 6.0))
body.append(gmirror("GB", "outa", "nvb_in", 0.2620))
body.append(pleg("AB", "nvb_in", 2.9854))
body.append(pleg("OB", "outb", 6.0))

# cell C: u_C = out_B: sink (out_B+6) 1:1 from nuc, add +6 const
#   (TIA inverts: u = -I(nu)/iu; sinking S makes I = -S -> u = +S/iu)
#   net u_C = (out_B+6) - 6 = out_B
body.append(gmirror("GC", "outb", "nuc", 1.0))
body.append(pleg("UC", "nuc", 6.0))
# wait: u_C = +(sunk) - (pushed)/... careful: I(nuc) = pushed - sunk
#   = 6 - (out_B+6) = -out_B -> u_C = +out_B  OK
# v_C: veff = 3: alpha = +1 unit
body.append(pleg("AC", "nvc_in", 1.0))
# out_C offset +6 (uniformity; subtract in analysis)
body.append(pleg("OC", "outc", 6.0))

body.append("""
.include /Users/cteusche/data/projects/eml/code/silicon/cell/v3/eml_cell_v3.inc
.include /Users/cteusche/data/projects/eml/code/silicon/cell/v3/eml_cell_v3b.inc
.include /Users/cteusche/data/projects/eml/code/silicon/bias/ptat_bias.inc

.control
set filetype=ascii
* PRESCALE x2: IX = 2x*iu (centers ln window); sweep HIGH->LOW
* (low-x end is below pedestal floor; never START a sweep there)
dc IX 12.4u 0.15u -0.05u
wrdata chain_full.csv i(VOUTC) i(VMON) i(VSDGB) i(VSDGC) i(VSPAV) i(VSNAV) v(nva_in) v(ndAV)
echo CHAIN_DONE
.endc
.end
""")

open("chain_full.spice", "w").write("\n".join(body))
print("chain_full.spice written")
